spring:
  application:
    name: jarvis-finance
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: localhost
    port: 6379

server:
  port: 8084

# 服务配置
finance:
  stock:
    cache:
      expiry: 600000  # 缓存过期时间（毫秒）
    api:
      sina:
        url: http://hq.sinajs.cn/list=

# 日志配置
logging:
  level:
    com.skyeai.jarvis.finance: info
